version: "3.1"
services:
  totem-postgres:
      build:
        context: .
        dockerfile: docker/database/Dockerfile
      container_name: totem-postgres
      volumes:
        - ./docker/database/postgres:/application/
        - ./docker/database/seeder.sql:/application/seeder.sql
        - ./docker/database/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      environment:
        - POSTGRES_USER=totem
        - POSTGRES_PASSWORD=totem
        - POSTGRES_DB=totem
        - PGDATA=/application/postgres
      ports:
        - "5432:5432"
      networks:
        - default

  totem-api:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: totem-api
    environment:
      - DATABASE_URL=postgresql://totem:totem@127.0.0.1:5432/totem
      - PORT=3000
    volumes:
      - ./docker/bin:/var/bin
    command: sh -c "npm install && chown -R www-data:www-data /var/www"
    depends_on: 
      - totem-postgres
    ports:
      - "3000:3000"
    links:
      - totem-postgres
    networks:
      - default

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
volumes:
  dbdata:
    driver: local